---
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Max: 30

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
