---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
